/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMaterialSymbolsKeyboardDoubleArrowRightRounded: typeof import('~icons/material-symbols/keyboard-double-arrow-right-rounded')['default']
    IMdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    IMdiArrowUp: typeof import('~icons/mdi/arrow-up')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCloseThick: typeof import('~icons/mdi/close-thick')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
